version: '3'

services:
  consul:
    image: consul
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"
    ports:
      - "8500:8500"
      - "8600:8600/udp"
  go-zookeeper:
    image: zookeeper
    container_name: go-zookeeper
    restart: unless-stopped
    ports:
      - 3013:2181

  # Kafka instance
  go-kafka:
    image: 'bitnami/kafka:latest'
    container_name: go-kafka
    restart: unless-stopped
    ports:
      - 3014:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=go-zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://go-kafka:9092,INTERNAL://go-kafka:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:3014,INTERNAL://go-kafka:29092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - go-zookeeper
  go-db:
    image: mysql:latest
    container_name: movieexample_db
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=movieexample
      - MYSQL_ROOT_PASSWORD=password

